# Zounce example configuration file
# ----------------------------------

title = "Zounce Configuration"
port = 7777

[logging]
    # TODO: Don't use SQLite if multiple users
    adapter = "SQLite3"
    database = "zounce"

[users]
    [users.zamn]
    nick = "zamn"
    altnick = "zamn92"
    username = "zamn"
    realname = "Adam"

    [users.zamn.auth]
    ca_path = "certs/ca.crt"

    [users.zamn.certs]

    # desktop pc
    [users.zamn.certs.desktop]
    cert_path = "certs/zamn.crt"

    [users.zamn.networks]

        [users.zamn.networks.GameSurge]
        servers = [
            "irc.gamesurge.net:6666"
        ]

        [users.zamn.networks.GameSurge.perform]
        channels = [
            "#zamN"
        ]

        # TODO: implement
        commands = [
            "/msg AuthServ@Services.Gamesurge.net user pass"
        ]

        # TODO: test freenode active chans
        # [users.zamn.networks.Freenode]
        # servers = ["irc.freenode.net:6666"]

